plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

name: &name "Andrew Vanis"
tile: *name
author:
  name: *name
  bio: "bio...."

theme: jekyll-theme-minimal